In [18]:
import pandas as pd

pd.options.display.max_columns = None

In [19]:
nombre = pd.read_csv('../../data/promesas/nombres_equipos.csv', index_col = 0)
nombre.head(2)

         Nombre jugador              Equipo actual
0         renzo-sanchez  club-nacional-de-football
1  dimitrios-keramitsis                       roma

In [20]:
caract = pd.read_csv('../../data/promesas/caracteristicas_jugadores.csv', index_col = 0)
caract.head(2)

   edad     pais
0    17  Uruguay
1    17   Greece

In [21]:
futuro = pd.read_csv('../../data/promesas/progresion_jugadores.csv', index_col = 0)
futuro.head(2)

   Valoración actual  Progresión
0                 62          80
1                 62          80

In [22]:
precio = pd.read_csv('../../data/promesas/precio_jugadores.csv', index_col = 0)
precio.head(2)

  precio
0    €1M
1  €925K

In [23]:
valorac = pd.read_csv('../../data/promesas/valoraciones_jugadores.csv', index_col = 0)
valorac.head(2)

,Valoración equipo actual,Mejor valoración individual,Ataque,Regate,Aceleración,Potencia tiro,Agresividad,Defensa,Portería
0,70,64,63,62,77,60,30,35,13
1,79,64,37,32,55,42,59,59,7

In [24]:
jovenespromesas = pd.concat([nombre, caract, futuro, precio, valorac], axis=1)
jovenespromesas

,Nombre jugador,Equipo actual,edad,pais,Valoración actual,Progresión,precio,Valoración equipo actual,Mejor valoración individual,Ataque,Regate,Aceleración,Potencia tiro,Agresividad,Defensa,Portería
0,renzo-sanchez,club-nacional-de-football,17,Uruguay,62,80,€1M,70,64,63,62,77,60,30,35,13
1,dimitrios-keramitsis,roma,17,Greece,62,80,€925K,79,64,37,32,55,42,59,59,7
2,ruben-iranzo-lendinez,valencia-cf,18,Spain,62,80,€950K,77,64,44,38,59,53,69,57,8
3,pelayo-gonzalez-rey,real-oviedo,16,Spain,62,81,€1M,69,65,42,60,66,60,69,54,9
4,antoni-djibu-milambo,feyenoord,16,Netherlands,62,80,€1M,75,64,56,69,70,60,44,41,15
5,el-chadaille-bitshiabu,paris-saint-germain,16,France,62,80,€925K,85,64,45,51,39,73,60,59,10
6,mohamed-sankoh,vfb-stuttgart,17,Netherlands,62,81,€1M,74,64,41,63,76,59,25,17,10
7,joao-grimaldo,club-sporting-cristal,18,Peru,62,81,€1M,68,64,55,63,71,66,45,44,10
8,brahim-traore,stade-malherbe-caen,17,France,62,80,€925K,68,64,27,32,64,37,58,62,8
9,luke-mbete,manchester-city,17,England,62,82,€1M,85,64,36,56,62,49,66,61,6
10,piotr-starzynski,wisla-krakow,17,Poland,62,80,€1M,65,63,60,62,83,58,39,24,13
11,bartug-elmaz,galatasaray-sk,18,Turkey,62,81,€950K,74,64,42,62,61,64,66,56,12
12,nene-dorgeles,sv-ried,18,Mali,62,81,€1M,64,64,42,68,82,67,42,35,6
13,bright-akwo-arrey-mbi,1-fc-koln,18,Germany,62,82,€1M,75,64,35,50,67,38,64,58,13
14,raul-moro-prescoli,lazio,18,Spain,62,80,€1M,79,64,51,69,74,53,40,30,7
15,bradley-fink,borussia-dortmund-ii,18,Switzerland,62,80,€1M,63,64,31,57,68,63,53,28,10
16,odin-thiago-holm,valerenga-fotball,18,Norway,62,80,€1M,66,65,51,65,72,52,45,41,14
17,nathan-wood,middlesbrough,19,England,62,80,€975K,70,64,30,40,71,36,60,64,14
18,ignacio-daniel-maestro-puch,atletico-tucuman,17,Argentina,61,80,€825K,69,63,37,56,65,64,46,13,6
19,tim-iroegbunam,aston-villa,18,England,61,81,€850K,78,62,51,59,64,68,62,58,13
20,jacopo-fazzini,empoli,18,Italy,61,81,€900K,72,63,52,65,65,69,64,54,9
21,siebe-wylin,kv-oostende,18,Belgium,61,82,€1M,69,61,59,57,76,42,57,54,10
22,pablo-felipe-pereira-de-jesus,futebol-clube-de-famalicao,17,Brazil,61,81,€900K,70,63,42,54,69,57,39,18,14
23,esey-gebreyesus,olympique-de-marseille,17,Switzerland,61,82,€1M,78,62,60,74,72,56,27,27,13
24,sean-mcgurk,leeds-united,18,England,61,80,€825K,76,63,54,59,73,59,43,41,5
25,kaide-gordon,liverpool,16,England,61,84,€1M,85,62,53,64,77,55,38,22,13
26,takuhiro-nakai,real-madrid-cf,17,Japan,61,83,€1M,84,63,42,70,53,53,37,31,9
27,salah-eddine-oulad-mhand,arsenal,17,Netherlands,61,80,€825K,80,63,58,62,72,59,40,40,14
28,gabriel-veiga-novas,rc-celta-de-vigo,19,Spain,61,81,€925K,76,64,37,65,69,67,43,34,13
29,santiago-castro,velez-sarsfield,16,Argentina,60,80,€675K,72,62,33,62,63,55,55,22,14
30,alberto-vaquero-aguilar,real-zaragoza,17,Spain,60,81,€775K,70,63,52,62,66,62,48,46,8
31,tommaso-de-nipoti,atalanta,17,Italy,60,80,€675K,80,61,50,70,65,55,39,22,12
32,antonio-foti,eintracht-frankfurt,17,Cyprus,60,80,€675K,77,64,49,64,69,60,52,49,15
33,filippo-missori,roma,17,Italy,60,81,€750K,79,60,59,63,62,33,54,52,11
34,alfie-devine,tottenham-hotspur,16,England,60,85,€775K,81,62,46,62,62,65,61,45,8
35,tyler-onyango,everton,18,England,60,80,€675K,78,62,45,58,63,63,69,44,15
36,mario-stroeykens,rsc-anderlecht,16,Belgium,60,82,€775K,72,62,46,68,68,58,21,18,7
37,rav-van-den-berg,pec-zwolle,16,Netherlands,60,81,€725K,66,62,30,55,57,47,53,55,13
38,josh-brooking,chelsea,18,England,60,80,€650K,84,62,39,39,63,47,57,55,8
39,nnamdi-collins,borussia-dortmund,17,Germany,60,82,€725K,81,62,44,44,83,33,56,53,12
40,kwadwo-baah,watford,18,Germany,60,80,€675K,74,61,49,62,87,64,50,30,10
41,cem-ali-dogan,dsc-arminia-bielefeld,16,Turkey,59,82,€700K,72,61,42,52,56,62,31,22,11
42,mateo-sanabria,club-atletico-lanus,17,Argentina,59,80,€700K,71,60,62,70,67,40,32,25,7
43,arnaud-dony,sint-truidense-vv,17,Belgium,59,82,€675K,68,60,58,59,76,32,60,51,10
44,lewis-hall,chelsea,16,England,59,80,€700K,84,63,60,61,73,53,60,59,14
45,cristian-riquelme,cd-everton-de-vina-del-mar,17,Chile,59,82,€675K,69,59,54,54,73,21,53,61,8
46,abdoulaye-kamara,borussia-dortmund,16,Guinea,59,82,€700K,81,62,47,67,66,58,56,49,6
47,jahkeele-marshall-rutty,toronto-fc,17,Canada,59,80,€675K,66,63,54,68,86,55,34,53,13
48,kervin-andrade,deportivo-la-guaira-fc,16,Venezuela,58,80,€650K,64,60,48,62,81,55,42,55,8
49,amar-ahmed-fatah,aik,17,Sweden,58,80,€650K,68,59,53,62,70,54,35,23,6
50,evan-ferguson,brighton-hove-albion,16,Republic of Ireland,58,80,€650K,76,60,40,57,70,56,45,14,9
51,ben-chrisene,aston-villa,17,England,58,81,€625K,78,61,61,73,74,48,45,54,5
52,enrique-herrero-garcia,eintracht-frankfurt,16,Spain,57,80,€525K,77,59,41,59,64,61,34,14,12
53,peder-hoel-lervik,molde-fk,16,Norway,56,81,€400K,67,56,14,13,40,47,23,13,61
54,joshua-feeney,aston-villa,16,England,55,81,€475K,78,57,37,32,55,47,51,50,11

In [25]:
jovenespromesas.to_csv('../../data/promesas/jovenespromesas.csv')